version: '3.4'

services: 
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports: 
      - 1433:1433
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSCOREONE_DB_PASSWORD}
    restart: on-failure
    volumes:
      - mssqldata:/var/lib/mssql

  redis:
    image: redis:alpine
    container_name: redis_db
    ports: 
      - 6379:6379
    volumes: 
      - ./redis-vol:/data
    restart: on-failure
volumes:
  mssqldata: