version: '3.4'

services: 
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports: 
      - 1433:1433
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSCOREONE_DB_PASSWORD}
    restart: on-failure
    volumes:
      - mssqldata:/var/lib/mssql

volumes:
  mssqldata: